= Kết luận

Tóm lại, AI là một lĩnh vực rất rộng và mới nổi lên gần đây. Tuy tạo ra nhiều kết quả đáng kinh ngạc, nhưng AI vẫn còn nhiều hạn chế trên các bài toán mang tính chuyên sâu. Cơ hội để Việt Nam có thể tham gia vào cuộc đua này là rất lớn, nhưng cần có sự đầu tư nghiêm túc từ các cơ quan chức năng, các doanh nghiệp và các nhà nghiên cứu.

Qua luận văn này, tôi đã nghiên cứu và hiểu hơn về lĩnh vực luật và các công cụ AI mới nhất hiện nay. Và thấy được tính khả thi khi áp dụng các công cụ AI này vào luật. Vì thiếu điều kiện, kinh phí để có thể thí nghiệm thêm, tôi chỉ có thể đưa ra một số ý tưởng và đề xuất cho các nghiên cứu sau này. Gồm 4 ý chính:

- *Xây dựng các bộ dữ liệu liên quan tới luật* như đã làm trong @phan3, tuy nhiên bộ dữ liệu mà tôi đã xây dựng chỉ mới là một phần nhỏ trong tất cả văn bản (chỉ bao gồm các văn bản liên quan tới bảo hiểm xã hội).  Và còn thiếu liên kết giữa các điều luật với nhau, ví dụ: Điều 28 luật hôn nhân 2014 *_được hướng dẫn_* bởi điều Điều 7 Nghị định 126/2014/NĐ-CP. Cần có một bộ dữ liệu đầy đủ hơn, bao gồm nhiều lĩnh vực pháp luật khác nhau, để có thể đưa ra được những kết quả chính xác nhất.

- *Xây dựng mô hình ngôn ngữ lớn (LLM) cho tiếng Việt*. Các mô hình hiện nay chỉ hoạt động tốt trên tiếng Anh, hay các ngôn ngữ la-tin. Cần có một mô hình dành riêng cho tiếng Việt. Anh Tiến Dũng, nhà sáng lập của Symato#footnote([Symato là một nhóm các nhà nghiên cứu và phát triển yêu tiếng Việt, chung tay phát triển mô hình ngôn ngữ lớn và công nghệ chatbot tiếng Việt. Được thành lập vào tháng 2/2023, tới cuối tháng 8/2023 nhóm đã có hơn 700 thành viên. #link("www.symato.xyz")]), hiện đang cùng đội ngũ huấn luyện một mô hình dành riêng cho tiếng Việt, dựa trên RWKV@PENG_RWKV-LM_2021 và tokenizer sử dụng âm tiết tiếng Việt. Do giới hạn về kinh phí nên nhóm của anh chỉ có thể huấn luyện mô hình với kích thước nhỏ, nhưng kết quả của mô hình này rất khả quan. Nếu có thể huấn luyện mô hình với kích thước lớn hơn, chắc chắn kết quả sẽ tốt hơn nhiều. Xem kết quả tại: https://github.com/telexyz/symato

- *Dùng LLM để sinh câu trả lời cho các câu hỏi liên quan tới luật*. Trong bài luận này, tôi có thử nghiệm để tìm ra các nội dung liên quan đến câu hỏi. Tuy nhiên, để đưa ra được câu hỏi có ý nghĩa, chính xác, cần ứng dụng các mô hình LLM.

- *Các vấn đề liên quan tới đạo đức, pháp lý khi sử dụng AI*. Cần có 1 phương pháp để kiểm soát những nội dung sinh ra từ AI. Sao cho nó không vi phạm đạo đức, pháp luật. Và cần có một cơ chế để kiểm soát, giám sát các mô hình AI. Để tránh việc các mô hình này bị lợi dụng, hay bị sử dụng sai mục đích.
